OpenConext/OpenConext-profile

.travis.yml
src/OpenConext/ProfileBundle/Security/Authentication/SamlInteractionProvider.php
src/OpenConext/ProfileBundle/Security/Firewall/SamlListener.php

Travis is configured to only run on (PRs to) master. Develop branch should be included as well.

Adds develop branch to .travis.yml

---

src/OpenConext/ProfileBundle/Resources/config/services.yml
src/OpenConext/ProfileBundle/Saml/StateHandler.php
src/OpenConext/ProfileBundle/Security/Firewall/SamlListener.php

[Ticket 108077998](https://www.pivotaltracker.com/story/show/108077998)

Move session migration from state handler to saml listener

---

src/OpenConext/ProfileBundle/Controller/IntroductionController.php
src/OpenConext/ProfileBundle/Controller/ProfileController.php
src/OpenConext/ProfileBundle/Controller/RemovalController.php
src/OpenConext/ProfileBundle/Controller/SamlController.php
src/OpenConext/ProfileBundle/Controller/ServicesController.php
src/OpenConext/ProfileBundle/DependencyInjection/Configuration.php
src/OpenConext/ProfileBundle/DependencyInjection/OpenConextProfileExtension.php
src/OpenConext/ProfileBundle/Resources/config/controllers.yml
src/OpenConext/ProfileBundle/Resources/config/routing.yml

[Ticket 108076226](https://www.pivotaltracker.com/story/show/108076226)

Controllers as services

---

app/config/global_view_parameters.yml.dist

These need to be added to OpenConext-deploy as well, but first they need to be documented a bit.

Document global view parameters

---

src/OpenConext/Profile/Tests/Value/EmailAddressTest.php
src/OpenConext/Profile/Value/EmailAddress.php
src/OpenConext/ProfileBundle/Resources/views/MyServices/overview.html.twig

[Ticket 106478068](https://www.pivotaltracker.com/story/show/106478068)

'Mailto:' should be added to hrefs when needed, but removed from displayed values

---

app/Resources/views/base.html.twig
src/OpenConext/ProfileBundle/Resources/views/layout.html.twig
web/css/lte-ie9.css
web/css/main.css

[Ticket 110246670](https://www.pivotaltracker.com/story/show/110246670)

Improve IE9 css

---

src/OpenConext/Profile/Entity/AuthenticatedUser.php
src/OpenConext/ProfileBundle/Security/Authentication/Provider/SamlProvider.php

Part of [Ticket #110497290](https://www.pivotaltracker.com/story/show/110497290)

Adds authenticating authorities to authenticated user

---

src/OpenConext/ProfileBundle/Resources/views/MyProfile/overview.html.twig
src/OpenConext/ProfileBundle/Resources/views/MyServices/overview.html.twig

[Ticket 108324754](https://www.pivotaltracker.com/story/show/108324754)
*Possible merge conflicts with other PRs*

Show urn on hover

---

app/config/config.yml
src/OpenConext/EngineBlockApiClientBundle/Repository/ConsentRepository.php
src/OpenConext/EngineBlockApiClientBundle/Repository/ContactPersonRepository.php
src/OpenConext/EngineBlockApiClientBundle/Resources/config/services.yml
src/OpenConext/EngineBlockApiClientBundle/Tests/Value/ConsentListFactoryTest.php
src/OpenConext/EngineBlockApiClientBundle/Tests/Value/ContactPersonListFactoryTest.php
src/OpenConext/EngineBlockApiClientBundle/Value/ConsentListFactory.php
src/OpenConext/EngineBlockApiClientBundle/Value/ContactPersonListFactory.php
src/OpenConext/Profile/Api/User.php
src/OpenConext/Profile/Entity/User.php
src/OpenConext/Profile/Exception/OutOfRangeException.php
src/OpenConext/Profile/Repository/ContactPersonRepository.php
src/OpenConext/Profile/Tests/Value/ContactPersonListTest.php
src/OpenConext/Profile/Tests/Value/ContactPersonTest.php
src/OpenConext/Profile/Tests/Value/ContactTypeTest.php
src/OpenConext/Profile/Value/ContactPerson.php
src/OpenConext/Profile/Value/ContactPersonList.php
src/OpenConext/Profile/Value/ContactType.php
src/OpenConext/Profile/Value/Entity.php
src/OpenConext/ProfileBundle/Controller/MyProfileController.php
src/OpenConext/ProfileBundle/DependencyInjection/Configuration.php
src/OpenConext/ProfileBundle/DependencyInjection/OpenConextProfileExtension.php
src/OpenConext/ProfileBundle/Resources/config/controllers.yml
src/OpenConext/ProfileBundle/Resources/config/services.yml
src/OpenConext/ProfileBundle/Resources/views/MyProfile/overview.html.twig
src/OpenConext/ProfileBundle/Service/SpecifiedConsentListService.php
src/OpenConext/ProfileBundle/Service/SupportContactEmailService.php
src/OpenConext/ProfileBundle/Service/UserService.php

[Ticket 110497290](https://www.pivotaltracker.com/story/show/110497290) and [106203816](https://www.pivotaltracker.com/story/show/106203816)

Add support contact email

---

app/AppKernel.php
app/config/config.yml
app/config/config_dev.yml
app/config/config_test.yml
app/config/parameters.yml.dist
composer.json
composer.lock
src/OpenConext/ProfileBundle/DependencyInjection/Configuration.php

[Ticket #106203464](https://www.pivotaltracker.com/story/show/106203464)

Setup email from and to

---

README.md
composer.json
composer.lock
makeRelease.sh

Added simple script, based on existing scripts within the platform, to create deployment tarballs.
Added documentation.

Add and document makeRelease.sh script and composer command

---

composer.json
composer.lock
src/OpenConext/Profile/Entity/AuthenticatedUser.php
src/OpenConext/Profile/Exception/InvalidEptiAttributeException.php
src/OpenConext/Profile/Exception/RuntimeException.php
src/OpenConext/Profile/Tests/Entity/AuthenticatedUserTest.php
src/OpenConext/ProfileBundle/Controller/MyServicesController.php
src/OpenConext/ProfileBundle/Service/ConsentService.php

Bugfix: parsing attributes

---

app/config/config.yml
app/config/parameters.yml.dist
src/OpenConext/ProfileBundle/DependencyInjection/Configuration.php
src/OpenConext/ProfileBundle/DependencyInjection/OpenConextProfileExtension.php
src/OpenConext/ProfileBundle/Resources/config/services.yml
src/OpenConext/ProfileBundle/Storage/SingleCookieStorage.php

OpenConext compatible locale cookie storage

---

app/Resources/translations/messages.en.xliff
app/Resources/translations/messages.nl.xliff

Update profile interface texts

---

app/Resources/translations/messages.en.xliff
app/Resources/translations/messages.nl.xliff
app/Resources/translations/saml.en.xliff
app/Resources/translations/saml.nl.xliff
app/config/global_view_parameters.yml.dist
src/OpenConext/ProfileBundle/Resources/config/services.yml
src/OpenConext/ProfileBundle/Resources/views/MyProfile/overview.html.twig
src/OpenConext/ProfileBundle/Service/GlobalViewParameters.php

Enrich Profile texts and translations with more links

---

README.md
composer.json
composer.lock

This version of Profile needs EB 5.2 as the EB Consent API has changed.

Update EngineBlock version requirement

---

app/Resources/translations/messages.en.xliff
app/Resources/translations/messages.nl.xliff
app/config/config.yml
app/config/parameters.yml.dist
src/OpenConext/ProfileBundle/Attribute/AttributeFilter.php
src/OpenConext/ProfileBundle/Controller/InformationRequestController.php
src/OpenConext/ProfileBundle/DependencyInjection/Configuration.php
src/OpenConext/ProfileBundle/DependencyInjection/OpenConextProfileExtension.php
src/OpenConext/ProfileBundle/Form/Type/InformationRequestMailType.php
src/OpenConext/ProfileBundle/Resources/config/controllers.yml
src/OpenConext/ProfileBundle/Resources/config/routing.yml
src/OpenConext/ProfileBundle/Resources/config/services.yml
src/OpenConext/ProfileBundle/Resources/views/InformationRequest/confirmation.html.twig
src/OpenConext/ProfileBundle/Resources/views/InformationRequest/email.html.twig
src/OpenConext/ProfileBundle/Resources/views/InformationRequest/overview.html.twig
src/OpenConext/ProfileBundle/Service/InformationRequestMailService.php
src/OpenConext/ProfileBundle/Tests/Attribute/AttributeFilterTest.php

On this page the user can confirm it's identity, a mail message with some basic account information is sent via email to a configurable email address.

Add hidden information-request page

---

composer.json
composer.lock
src/OpenConext/Profile/Entity/AuthenticatedUser.php
src/OpenConext/Profile/Tests/Entity/AuthenticatedUserTest.php
src/OpenConext/ProfileBundle/Attribute/AttributeSetWithFallbacks.php
src/OpenConext/ProfileBundle/Security/Authentication/SamlInteractionProvider.php
src/OpenConext/ProfileBundle/Security/Authentication/Token/SamlToken.php
src/OpenConext/ProfileBundle/Security/Firewall/SamlListener.php
src/OpenConext/ProfileBundle/Tests/Attribute/AttributeSetWithFallbacksTest.php

Upgrades the Stepup-saml-bundle to version 3.0.0-rc2

Stepup saml bundle upgrade

---

README.md
app/Resources/TwigBundle/views/Exception/error.html.twig
app/Resources/TwigBundle/views/Exception/error403.html.twig
app/Resources/TwigBundle/views/Exception/error404.html.twig
app/Resources/translations/messages.en.xliff
app/Resources/translations/messages.nl.xliff

See: https://www.pivotaltracker.com/story/show/155549384

Add custom error templates for 403, 404 and 500 errors

---

composer.lock

This will help to mitigate CVE's:
* CVE-2018-11386: CVE-2018-11386: Denial of service when using PDOSessionHandler
https://symfony.com/cve-2018-11386
* CVE-2018-11406: CVE-2018-11406: CSRF Token Fixation
https://symfony.com/cve-2018-11406
* CVE-2018-11408: CVE-2018-11408: Open redirect vulnerability on security handlers
https://symfony.com/cve-2018-11408
* CVE-2018-11385: CVE-2018-11385: Session Fixation Issue for Guard Authentication
https://symfony.com/cve-2018-11385

Upgrade Symfony to 2.7.48

---

README.md
app/AppKernel.php
app/Resources/translations/messages.en.xliff
app/Resources/translations/messages.nl.xliff
app/Resources/translations/saml.en.xliff
app/Resources/translations/saml.nl.xliff
app/config/config.yml
app/config/parameters.yml.dist
src/OpenConext/ProfileBundle/Controller/MySurfConextController.php
src/OpenConext/ProfileBundle/DependencyInjection/OpenConextProfileExtension.php
src/OpenConext/ProfileBundle/Resources/config/routing.yml
src/OpenConext/ProfileBundle/Resources/config/services.yml
src/OpenConext/ProfileBundle/Resources/views/MySurfConext/overview.html.twig
src/OpenConext/ProfileBundle/Service/UserService.php
src/OpenConext/UserLifecycleApiClientBundle/DependencyInjection/Configuration.php
src/OpenConext/UserLifecycleApiClientBundle/DependencyInjection/OpenConextUserLifecycleApiClientExtension.php
src/OpenConext/UserLifecycleApiClientBundle/Exception/InvalidArgumentException.php
src/OpenConext/UserLifecycleApiClientBundle/Exception/InvalidResponseException.php
src/OpenConext/UserLifecycleApiClientBundle/Exception/LogicException.php
src/OpenConext/UserLifecycleApiClientBundle/Exception/MalformedResponseException.php
src/OpenConext/UserLifecycleApiClientBundle/Exception/OpenConextUserLifecycleApiClientException.php
src/OpenConext/UserLifecycleApiClientBundle/Exception/ResourceNotFoundException.php
src/OpenConext/UserLifecycleApiClientBundle/Exception/RuntimeException.php
src/OpenConext/UserLifecycleApiClientBundle/Http/JsonApiClient.php
src/OpenConext/UserLifecycleApiClientBundle/OpenConextUserLifecycleApiClientBundle.php
src/OpenConext/UserLifecycleApiClientBundle/Resources/config/services.yml
src/OpenConext/UserLifecycleApiClientBundle/Tests/DataProvider.php
src/OpenConext/UserLifecycleApiClientBundle/Tests/DependencyInjection/HttpClientConfigurationTest.php
src/OpenConext/UserLifecycleApiClientBundle/Tests/Http/JsonApiClientTest.php
web/css/main.css

Profile users are now able to dowload their SURFconext platform data.
See: https://www.pivotaltracker.com/story/show/158761196

Implement user lifecycle data download

---

src/OpenConext/Profile/Tests/Value/UrlTest.php
src/OpenConext/Profile/Value/Url.php

Makes it a bit less of a wild goose chase to find the one invalid URL in
the database.

Log which URL failed validation.

---

composer.lock

This mitigates the following CVE vulnerabilities:
symfony/symfony (v2.7.50)
-------------------------
* [CVE-2019-10909][]: Escape validation messages in the PHP
templating engine
* [CVE-2019-10910][]: Check service IDs are valid
* [CVE-2019-10911][]: Add a separator in the remember me
cookie hash
* [CVE-2019-10913][]: Reject invalid HTTP method overrides
twig/twig (v1.37.1)
-------------------
* [CVE-NONE-0001][]: Sandbox Information Disclosure
[CVE-2019-10909]: https://symfony.com/cve-2019-10909
[CVE-2019-10910]: https://symfony.om/v-2019-10910
[CVE-2019-10911]: https://symfony.com/cve-2019-10911
[CVE-2019-10913]: https://symfony.com/cve-2019-10913
[CVE-NONE-0001]:
https://symfony.com/blog/twig-sandbox-information-disclosure

Install Symfony and Twig security updates

---

app/Resources/translations/messages.pt.xliff

comparing the Portuguese messages and the new English messages there were missing some quotes and were some bad configs as well

added some Portuguese messages

---

composer.json
composer.lock

As requested in https://www.pivotaltracker.com/story/show/165853784

Bump Stepup SAML bundle to version 4.1.4

---

app/Resources/translations/messages.en.xliff
app/Resources/translations/messages.pt.xliff

The information on the data retention limit was invalid.
https://www.pivotaltracker.com/story/show/167494241

Fix the data retention translation

---

ansible/roles/app/tasks/main.yml
build.xml
package-lock.json

Fix Npm security issues and add a newer version of Nodejs and Ant
to the development Ansible to be able to run the audit tools in our
development environment. A newer version of Npm was needed to be able
to run `npm audit fix`.
https://www.pivotaltracker.com/story/show/168473817

Fix npm security issues

---

composer.lock

Prior to this change, we were three versions behind on the stepup/saml-bundle
This change updates the bundle to the latest version.
Pivotal ticket @ https://www.pivotaltracker.com/story/show/175161599

Upgrade stepup/saml-bundle to latest version

---

app/config/parameters.yml.dist
package-lock.json
package.json

Prior to this change, the lang cookie was set to unsecure by default.
This change ensures secure is on by default for the lang cookie.
Pivotal ticket @ https://www.pivotaltracker.com/story/show/177477798

Add secure flag to lang cookie

---

app/Resources/translations/messages.pt.yml

the messages where translated to Portuguese and deleted the FIXME tag

translation to Portuguese

---

app/Resources/translations/messages.en.yml
app/Resources/translations/messages.nl.yml
app/Resources/translations/messages.pt.yml
app/web/css/components/components.scss
app/web/css/components/idprow.scss
app/web/css/helpers/mixins.scss
src/OpenConext/ProfileBundle/Controller/MyServicesController.php
src/OpenConext/ProfileBundle/Resources/views/MyServices/AttributeList/idp.html.twig
src/OpenConext/ProfileBundle/Resources/views/helpers/correction.html.twig

Prior to this change, there was no provided by row.
This change adds one.
https://app.zeplin.io/project/5ddd2a806dea441ba05ae87a/screen/60def987289fd43e1d0f3920

Add the provided by row in my services

---

.env.dist
.env.test
.gitignore
README.md

The .env file was removed from the repo and a .env.dist file was used instead. This was also administrated in the README.md file.

Correctly set the .env settings

---

.github/workflows/main.yml
docker/Dockerfile

This will use the Docker containers which are built in the OpenConext-container project.

Docker: Use OpenConext containers to build the production containers

---

composer.json
composer.lock

This starts exposing the opcache status

Update OpenConext Monitor Bundle

---

ci/npm-audit.sh
package-lock.json
src/OpenConext/EngineBlockApiClientBundle/Repository/InstitutionRepository.php
src/OpenConext/Profile/Tests/Value/LogoTest.php
src/OpenConext/Profile/Tests/Value/OrganizationTest.php
src/OpenConext/Profile/Value/Logo.php
src/OpenConext/Profile/Value/Organization.php
src/OpenConext/ProfileBundle/Controller/MyServicesController.php
src/OpenConext/ProfileBundle/Resources/config/services.yml
src/OpenConext/ProfileBundle/Resources/views/MyServices/AttributeList/idp.html.twig
src/OpenConext/ProfileBundle/Resources/views/MyServices/ConsentList/consent-list.html.twig
translations/messages.en.php
translations/messages.nl.php
translations/messages.pt.php

Prior to this change the institution was always shown as "Ibuildings university" with the surf logo.
This change ensures we retrieve the correct data from the engineblock api and show it in the my services view.
Pivotal ticket @ https://www.pivotaltracker.com/story/show/180095716

Use correct institution data

---

composer.lock
package-lock.json
package.json

The JS and PHP dependencies are updated to stay up to date with everything

Install periodic security upgrades

---

src/OpenConext/ProfileBundle/Resources/views/translations.html.twig
translations/messages.en.php
translations/messages.nl.php
translations/messages.pt.php

BSR: remove obsolete surfmarket_entitlements name.

Add support for 'invite' attribute source.
