OpenConext/OpenConext-profile

src/OpenConext/ProfileBundle/Saml/StateHandler.php
Probably missed this because my session was already loaded.
=> Removes last session_path usage from StateHandler class

ansible/roles/php/tasks/main.yml
[Bugfix, ticket 106924668](https://www.pivotaltracker.com/story/show/106924668)
Apparently, a startup script is not setup automatically by PHP-FPM. Chkconfig allows us to do so.
More info on [chkconfig](http://linux.die.net/man/8/chkconfig):
> chkconfig provides a simple command-line tool for maintaining the /etc/rc[0-6].d directory hierarchy by relieving system administrators of the task of directly manipulating the numerous symbolic links in those directories.
> (...)
>   If one of on, off, reset, or resetpriorities is specified after the service name, chkconfig changes the startup information for the specified service.
> (...)
=> Configure PHP-FPM to run on boot

ansible/roles/php/tasks/main.yml
[Ticket 106924668](https://www.pivotaltracker.com/story/show/106924668)
Improves #11 by using Ansible's (abstracted) service module instead of chkconfig.
=> Uses service instead of command to start php-fpm on boot

src/OpenConext/EngineBlockApiClientBundle/Tests/Value/ConsentListFactoryTest.php, src/OpenConext/EngineBlockApiClientBundle/Value/ConsentListFactory.php, src/OpenConext/Profile/Tests/Value/ConsentTypeTest.php, src/OpenConext/Profile/Tests/Value/EmailAddressTest.php, src/OpenConext/Profile/Tests/Value/EntityIdTest.php, src/OpenConext/Profile/Tests/Value/EntityTest.php, src/OpenConext/Profile/Tests/Value/EntityTypeTest.php, src/OpenConext/Profile/Tests/Value/UrlTest.php, src/OpenConext/Profile/Value/Consent.php, src/OpenConext/Profile/Value/ConsentType.php
[Ticket 106401530](https://www.pivotaltracker.com/story/show/106401530)
In order to show the consent type on the services page, it is added to the consent object.
Blocked by: [PR EB #219](https://github.com/OpenConext/OpenConext-engineblock/pull/219)
=> Retrieve consent type

src/OpenConext/ProfileBundle/Resources/config/services.yml, src/OpenConext/ProfileBundle/Saml/StateHandler.php
When removing the session migration from the Saml StateHandler, the session object itself has not been removed. This PR cleans that up.
=> Removes unused session in StateHandler

web/css/main.css
[Ticket 109071222](https://www.pivotaltracker.com/story/show/109071222)
Makes table look more like older version with smaller fonts and a darker background.
Also prevents table head from getting highlighted.
*Possible merge conflicts with other PRs*
=> Restyle attributes in services table

.travis.yml, README.md, build.xml, composer.json, composer.lock, src/OpenConext/Profile/Entity/AuthenticatedUser.php, src/OpenConext/Profile/Exception/InvalidEptiAttributeException.php, src/OpenConext/Profile/Tests/Entity/AuthenticatedUserTest.php
At Ibuildings we would like to take a more proactive role at monitoring and alerting for security updates of the software we create and deliver to customers.
As part of this, for this project we'd like to:
* Upgrade to the latest patch level of Symfony 2.7
* Turn on the security checker and make it fail pull requests.
Unfortunately I had to do a full composer update as Composer got lost with all the interdependencies.
Please see the commit for a full overview of all upgraded packages.
Also we'd like to turn on nightly builds ( https://docs.travis-ci.com/user/cron-jobs/ ), though I think I can request this from Travis.
=> Turn on security checker and do composer update

app/config/config.yml
This should be configured on the server level in production, see OpenConext-Deploy
#54
=> Drop setting HSTS header

composer.json, composer.lock, src/OpenConext/Profile/Entity/AuthenticatedUser.php, src/OpenConext/ProfileBundle/Attribute/AttributeSetWithFallbacks.php, src/OpenConext/ProfileBundle/Resources/views/MyServices/overview.html.twig, src/OpenConext/ProfileBundle/Security/Authentication/Provider/SamlProvider.php, src/OpenConext/ProfileBundle/Tests/Attribute/AttributeSetWithFallbacksTest.php
This implements #55 in Profile, using the ConfigurableAttributeSetFactory from SURFnet/Stepup-saml-bundle#51.
As shown in the image below, an undefined attribute will use its urn as a name in the My Services table (in this case I removed the definition for the "surfconext status" for testing purposes). It will not throw an exception.
=> Implement attribute set with fallbacks

src/OpenConext/ProfileBundle/Resources/views/MyProfile/overview.html.twig
This has already been done in the [My Services template](https://github.com/OpenConext/OpenConext-profile/blob/d6a0ede4a93203823efe631fc993c230a51d6637/src/OpenConext/ProfileBundle/Resources/views/MyServices/overview.html.twig#L79-L85).
=> Remove translation key from undefined attributes

src/OpenConext/EngineBlockApiClientBundle/Service/AttributeReleasePolicyService.php
Because we do not have any guarantees the definitions are to be found in the dictionary, we apply the same fallback mechanism as used in the AttributeSetWithFallbacks.
=> Support fallbacks for attribute definitions in ARP service

app/Resources/translations/messages.en.xliff, app/Resources/translations/messages.nl.xliff, composer.lock, src/OpenConext/EngineBlockApiClientBundle/Tests/Value/ConsentListFactoryTest.php, src/OpenConext/EngineBlockApiClientBundle/Value/ConsentListFactory.php, src/OpenConext/Profile/Value/Consent.php, src/OpenConext/ProfileBundle/Resources/views/MyServices/overview.html.twig, src/OpenConext/ProfileBundle/Tests/Service/AttributeReleasePolicyServiceTest.php
[130002585](https://www.pivotaltracker.com/story/show/130002585)
OpenConext/OpenConext-engineblock#316
OpenConext/OpenConext-engineblock#367
This PR switches the last used consent date with the first used consent date as per the changes in the new Consent API, see linked issues and PRs.
=> Switch last used with first used consent date

src/OpenConext/ProfileBundle/Resources/views/MyProfile/overview.html.twig, src/OpenConext/ProfileBundle/Resources/views/MyServices/overview.html.twig
To get a multi value attribute hack the following into `\OpenConext\Profile\Entity\AuthenticatedUser::createFrom` on line 67:
`$attributes[] = new Attribute($definition, [$eptiValues[0]['Value'], 'Foobar', 'Lorem ipsum']);`
The story only spoke about changing the my profile page. I've taken the liberty to apply the same logic to the my services attribute lists.
=> Separate multi valued attributes with newline

src/OpenConext/Profile/Entity/AuthenticatedUser.php, src/OpenConext/Profile/Tests/Entity/AuthenticatedUserTest.php
The urn:oid:1.3.6.1.4.1.1076.20.40.40.1 and urn:oid:1.3.6.1.4.1.1466.115.121.1.15 attributes are not to be shown to end users. These attributes are only kept for historic reasons. So filter them when evaluating their attributes.
A test was added to ascertain the attribute filtering actually works.
**Test instructions**
When logging in with a mujina student before you will see two Organization attributes in the my profile attribute listing.
After applying the changes of this PR, one of them is no longer present.
=> Filter blacklisted attributes

app/Resources/translations/messages.en.xliff, app/Resources/translations/messages.nl.xliff, src/OpenConext/EngineBlockApiClientBundle/Service/AttributeReleasePolicyService.php, src/OpenConext/Profile/Entity/AuthenticatedUser.php, src/OpenConext/Profile/Tests/Value/SpecifiedConsentTest.php, src/OpenConext/Profile/Value/AttributeAggregation/AttributeAggregationAttribute.php, src/OpenConext/Profile/Value/SpecifiedConsent.php, src/OpenConext/ProfileBundle/Resources/views/MyServices/AttributeList/aa.html.twig, src/OpenConext/ProfileBundle/Resources/views/MyServices/AttributeList/idp.html.twig, src/OpenConext/ProfileBundle/Resources/views/MyServices/overview.html.twig, src/OpenConext/ProfileBundle/Resources/views/translations.html.twig, src/OpenConext/ProfileBundle/Service/SpecifiedConsentListService.php, src/OpenConext/ProfileBundle/Tests/Service/AttributeReleasePolicyServiceTest.php, web/css/main.css
Sources are retrieved from Engineblock Api. The changes are built on top of the changes made in `feature/account-linking-information`. 
**Test instructions**
I've updated one of the services in service registry to apply the arp. And then configured some attribute sources to originate from voot/sab.
Also see this [EB PR](https://github.com/OpenConext/OpenConext-engineblock/pull/457)
=> Show sources of attributes in my services overview

app/AppKernel.php, app/config/routing.yml, app/config/security.yml, composer.json, composer.lock, src/OpenConext/EngineBlockApiClientBundle/HealthCheck/ApiHealthCheck.php, src/OpenConext/EngineBlockApiClientBundle/Resources/config/services.yml
The health and info responses can be requested at respectively: hostname/health and hostname/info
The endpoints are not restricted by firewall rules and thus are publically available. This should be restricted by the load balancer.
The bundle is extended with an extra health checker for the engine block API. For now, a consent request is performed for a nonexistent user. This is less than elegant and preferably the engine endpoints receive a health endpoint themselves.
=> Install Monitor bundle

app/config/config.yml, src/OpenConext/Profile/Value/AttributeAggregation/AttributeAggregationAttribute.php, src/OpenConext/Profile/Value/AttributeAggregation/AttributeAggregationAttributeConfiguration.php, src/OpenConext/Profile/Value/AttributeAggregation/AttributeAggregationAttributesList.php, src/OpenConext/Profile/Value/AttributeAggregation/AttributeAggregationEnabledAttributes.php, src/OpenConext/ProfileBundle/Resources/views/MyConnections/overview.html.twig, src/OpenConext/ProfileBundle/Service/AttributeAggregationService.php
Asking the attribute aggregator for a list of connected accounts
returns a response like:
[
{
"accountType" : "ORCID",
"created" : 1509708987,
"id" : 50,
"linkedId" : "http://orcid.org/0000-0002-5385-9420",
"schacHome" : "surfnet.nl",
"urn" : "urn:collab:person:surfnet.nl:kinkhorst"
}
]
Previous implementation expected an ARP reply, which is not how
profile obtains the connection status of linked accounts. Major
difference is that we now configure the accountType (ORCID) instead of
the urn of the attribute and match that to the account list.
=> Support account list in attribute aggregator response

src/OpenConext/ProfileBundle/Resources/views/MyServices/AttributeList/idp.html.twig, web/css/main.css
**Review notes**
The attribute values were retrieved using the getValue method on the
Attribute class (SAML2 Assertion). This returned the attributes in an
aggregated manner. When iterating the attribute values, all values
are displayed in a paragraph without margin. Ensuring attributes with
multiple values are displayed beneath each other.
**Test note**
To test with attributes with multiple values do the following:
Open: `src/OpenConext/ProfileBundle/Attribute/AttributeSetWithFallbacks.php`
Just above line 43, you can add `attributeValues` to the existing values array. This could look like this: 
```php
public static function createFrom(SAML2_Assertion $assertion, AttributeDictionary $attributeDictionary)
{
$attributeSet = new AttributeSetWithFallbacks();
foreach …
```
=> Show attribute values in paragraphs

app/Resources/translations/messages.en.xliff, app/Resources/translations/messages.nl.xliff, src/OpenConext/Profile/Value/AttributeAggregation/AttributeAggregationAttributesList.php, src/OpenConext/ProfileBundle/Controller/MyConnectionsController.php, src/OpenConext/ProfileBundle/Resources/views/MyConnections/overview.html.twig
**Testing notes**
The changes to the `MyConnectionsController::overviewAction` make it easier to show connections in different states. Some test examples can be:
```php
// Hide any active connections (show the no available connections)
return new Response($this->templateEngine->render(
'OpenConextProfileBundle:MyConnections:overview.html.twig',
[
'activeConnections' => [],
'availableConnections' => $availableConnections,
'mailTo' => $this->mailTo->getEmailAddress(),
]
));
// Hide all connections
return new Response($this->templateEngine->render(
'OpenConextProfileBundle:MyConnections:overview.html.twig',
[
'activeConnections' => [],
'availableConnections' => [],
'mailTo' => $this->mailTo->getEmailAddress(),
]
));
```
For more details on the specific texts that have been changed see the …
=> Changes to texts on the my connections page

app/Resources/translations/saml.en.xliff, composer.lock, src/OpenConext/EngineBlockApiClientBundle/Service/AttributeReleasePolicyService.php, src/OpenConext/Profile/Exception/InvalidArpDataException.php, src/OpenConext/Profile/Tests/Value/ArpTest.php, src/OpenConext/Profile/Tests/Value/SpecifiedConsentTest.php, src/OpenConext/Profile/Tests/fixture/arp-response.json, src/OpenConext/Profile/Value/Arp.php, src/OpenConext/Profile/Value/SpecifiedConsent.php, src/OpenConext/ProfileBundle/Tests/Service/AttributeReleasePolicyServiceTest.php
**Test notes**
Enable ARP for an SP you can use (I've used teams). And set sources different than idp on some of the attributes. Log in to the service you just modified and then check the my services page in Profile. 
Update your EB installation by checking out the `feature/eb-api-read-arp-endpoint` feature branch.
A new release for the Saml bundle was released and installed (2.11.2). Make sure you update your composer dependencies.
**Work checklist**
=> Show attributes from AA sources in My Services

README.md, app/Resources/translations/messages.en.xliff, app/Resources/translations/messages.nl.xliff, src/OpenConext/ProfileBundle/Resources/views/translations.html.twig
The source name was added to the translations. And a readme entry was 
I've added a brief summary of this task to the readme as adding AA sources might become a common task in the future.
=> Add AA source support for SURFmarked Entitlements

src/OpenConext/EngineBlockApiClientBundle/Service/AttributeReleasePolicyService.php, src/OpenConext/ProfileBundle/Tests/Service/AttributeReleasePolicyServiceTest.php
A recent change in the EngineBlock api dictates that the read-api
endpoint should be used using POST requests. This commit fixes that
for Profile.
This is part of bugfix: https://www.pivotaltracker.com/story/show/155497459
=> Post read-api requests

src/OpenConext/ProfileBundle/Resources/config/services.yml, src/OpenConext/ProfileBundle/Security/Firewall/SamlListener.php
When a SSO action is initiated by profile but not completed by the
user, profile throws a server error on subsequent visits to profile.
This commit re-initiates the SSO action if the previous action was not
completed.
See: https://www.pivotaltracker.com/story/show/154839079
=> Don't error when single-signon is not completed

app/config/config.yml, app/config/config_dev.yml, app/config/config_test.yml, makeRelease.sh
Symfony automatically appends the cache buster using the value
configured in config.yml. This defaults to 'dev' or 'test' on those
environments, and the release tarball contains the git version of the
release.
See: https://www.pivotaltracker.com/story/show/154996487
=> Append a cache-buster to all frontend assets

src/OpenConext/ProfileBundle/Resources/views/translations.html.twig
The attribute was forgotten in commit a00d306. This makes sure a
translation scan won't delete the translation from the xliff file.
=> Add eduPersonOrcid translation to translations template

app/Resources/translations/messages.en.xliff, app/Resources/translations/messages.nl.xliff, src/OpenConext/EngineBlockApiClientBundle/Tests/Value/ConsentListFactoryTest.php, src/OpenConext/EngineBlockApiClientBundle/Value/ConsentListFactory.php, src/OpenConext/Profile/Tests/Value/SpecifiedConsentTest.php, src/OpenConext/Profile/Value/Consent/ServiceProvider.php, src/OpenConext/Profile/Value/NameIdFormat.php, src/OpenConext/ProfileBundle/Resources/views/MyServices/AttributeList/idp.html.twig, src/OpenConext/ProfileBundle/Tests/Service/AttributeReleasePolicyServiceTest.php
This requires EB5.5.2 after hotfix1, or EB>5.5.4 or EB>5.6.3 or EB>=5.7.
Quick summary of how this works:
- EB sends the configured NameIDFormat of the SP in the response of the /consent API call
- profile shows the italic 'transient' message instead of the eduPersonTargetedID if the format is transient
- profile shows the italic 'persistent' message instead of the eduPersonTargetedID if the format is persistent
- values which are not transient or persistent nameIDs (unspecified, email, ...) are shown in the attributes table as-is
See: https://www.pivotaltracker.com/story/show/154912300
And: https://github.com/OpenConext/OpenConext-engineblock/pull/519
=> Don't show transient and persistent name IDs

app/Resources/translations/messages.en.xliff, app/Resources/translations/messages.nl.xliff, src/OpenConext/EngineBlockApiClientBundle/Tests/Value/ConsentListFactoryTest.php, src/OpenConext/EngineBlockApiClientBundle/Value/ConsentListFactory.php, src/OpenConext/Profile/Tests/Value/SpecifiedConsentTest.php, src/OpenConext/Profile/Value/Consent/ServiceProvider.php, src/OpenConext/Profile/Value/NameIdFormat.php, src/OpenConext/ProfileBundle/Resources/views/MyServices/AttributeList/idp.html.twig, src/OpenConext/ProfileBundle/Resources/views/MyServices/overview.html.twig, src/OpenConext/ProfileBundle/Tests/Service/AttributeReleasePolicyServiceTest.php
Note: this PR includes #101, so test that one first!
This requires EB5.5.2 after hotfix1, or EB>5.5.4 or EB>5.6.3 or EB>=5.7.
The EB consent API now sends the support urls (en/nl) along with the consent data, and this is displayed on the 'My Services' page.
See: https://www.pivotaltracker.com/story/show/107474726
And: OpenConext/OpenConext-engineblock#520
=>  Display the support URL on 'My Services' 

src/OpenConext/EngineBlockApiClientBundle/Tests/Value/ContactPersonListFactoryTest.php, src/OpenConext/EngineBlockApiClientBundle/Value/ContactPersonListFactory.php, src/OpenConext/Profile/Value/ContactPersonList.php
The ContactPersonList initialized in an invalid state when created
with an empty array. It is now possible to have a list object without
contacts in it.
Another measure taken in this commit, although not required, is not
trusting EngineBlock to send an empty array in the case there are no
contacts.
Fixes #94
See: https://www.pivotaltracker.com/story/show/155390093
=> Allow IDP metadata without contacts

src/OpenConext/EngineBlockApiClientBundle/Tests/Value/ConsentListFactoryTest.php, src/OpenConext/EngineBlockApiClientBundle/Value/ConsentListFactory.php
EB previously sent the support URL in the 'support_url' and
'support_url_*' fields, the latter was removed in EB5.7 and this
commit updates profile to support that change.
See https://github.com/OpenConext/OpenConext-engineblock/pull/532
=> Remove duplicate 'support_url' in consent API response

app/Resources/translations/messages.en.xliff, app/Resources/translations/messages.nl.xliff, src/OpenConext/Profile/Tests/Value/ArpTest.php, src/OpenConext/Profile/Value/Arp.php, src/OpenConext/Profile/Value/SpecifiedConsent.php, src/OpenConext/ProfileBundle/Resources/views/MyServices/AttributeList/idp.html.twig
This PR changes two things
1. The my services screen no longer breaks when attribute motivations are returned from the `read-arp` engine block API endpoint. This was fixed by making the response validation more tolerant. Now only the value entry is actively tested. The source and motivation are optional.
2. The motivation is displayed in the 'my services' overview.
The Pivotal story: https://www.pivotaltracker.com/story/show/158522286
=> Include arp motivations

README.md, src/OpenConext/Profile/Tests/Entity/AuthenticatedUserTest.php, src/OpenConext/ProfileBundle/Resources/config/services.yml, src/OpenConext/ProfileBundle/Service/ConsentService.php
The nameId value is now used instead. Containing the exact same value
as long as the NameID was configured to be unspecified (which it is in
our case).
The NameID can already be read from the AuthenticatedUser object, so
manually retrieving it from the assertion subject is not required.
The ConsentService could be cleaned up drastically.
https://www.pivotaltracker.com/story/show/164103691
=> Stop using SURFconextId as user identifier

composer.json, composer.lock, src/OpenConext/Profile/Tests/Entity/AuthenticatedUserTest.php
Fix the security warnings that are reported by the security checker.
Note that we use the SimpleSAMLphp SAML2 library at version 3.2 until 3.3 is considered stable.
=> Security updates

app/config/config.yml, app/config/parameters.yml.dist, src/OpenConext/Profile/Assert.php, src/OpenConext/Profile/Tests/AssertTest.php, src/OpenConext/ProfileBundle/Service/GlobalViewParameters.php
The available locales must now be configured in the parameters.yml file. Previously we configured them in the main config file (in a parameters section). This change enables us to be more flexible in enabling/disabling languages. This would previously result in a VCS change.
The drawback of this is that we can enable/disable languages that might not be (fully) supported. This was previously more rigorously verified in the GlobalViewParameters VO.
=> Make locales configurable

.travis.yml
This is done in order to be able to test behavior on PHP 7.2 & 7.3 to explore possible PHP migration issues.
=> Test against PHP 7.2 and 7.3 with Travis

app/config/global_view_parameters.yml.dist, app/config/parameters.yml.dist, src/OpenConext/ProfileBundle/Resources/views/MyConnections/overview.html.twig
The asset paths where not set correctly, they needed to have the /build
prefix. This would prevent the images from loading correctly in prod
mode, but would work in development environments.
=> Add /build to asset paths

app/Resources/translations/messages.en.xliff, app/Resources/translations/messages.nl.xliff, app/Resources/translations/messages.pt.xliff, app/Resources/translations/saml.en.xliff, app/Resources/translations/saml.nl.xliff, app/Resources/translations/saml.pt.xliff, bin/extract-translations.sh, src/OpenConext/ProfileBundle/Resources/views/translations.html.twig
The translation was missing for the Saml attribute. This is now fixed.
https://www.pivotaltracker.com/story/show/167191228
=> Add ECK ID saml attribute translation

src/OpenConext/ProfileBundle/Resources/views/MyConnections/overview.html.twig, web/css/main.css
The login button doesn't fit on small screens even if they aren't that
small. Now the button is placed above the connection so it will fit.
=> Optimize ORCiD button placement for all devices

.travis.yml, CHANGELOG.md, composer.json, composer.lock
This change will apply the countermeasures to harden against
CVE 2019-3465 and will effectively bump `robrichards/xmlseclibs` to
version 3.0.4.
=> Upgrade xmlseclibs to version 3.0.4

CHANGELOG.md, composer.json, composer.lock
This change will apply the countermeasures to harden against
CVE 2019-3465 and will effectively bump robrichards/xmlseclibs to
version 3.0.4.
=> Upgrade Stepup-saml-bundle to version 4.1.8

package-lock.json, package.json
A security audit via npm audit yielded no less then 777 vulnerabilities.
This change implements fixes for those vulnerabilities.  Using npm audit fix, upgrading the webpack encore version and a resolution for the final vulnerability.
Pivotal ticket @ https://www.pivotaltracker.com/story/show/176872945
=> Fix security audit errors

app/Resources/translations/messages.en.yml, app/Resources/translations/messages.nl.yml, app/Resources/translations/messages.pt.yml, app/web/css/components/components.scss, app/web/css/components/modal-window.scss, app/web/css/helpers/mixins.scss, app/web/css/main.scss, app/web/css/pages/myConnections/myConnections.scss, app/web/js/app.js, app/web/js/modalWindow.js, app/web/js/my-connections.js, src/OpenConext/ProfileBundle/Form/Type/ConfirmConnectionDeleteType.php, src/OpenConext/ProfileBundle/Resources/views/MyConnections/active-connections.html.twig
Prior to this change, the old layout was still used.  The new design calls for a modal.
This change ensures the modal with the propper design is used.  It also ensures the modal is fully accessible.
The modal technique was taken from this example: https://tutorialspage.com/create-modal-window-pure-html5-css3/
The modal trap was modified from code found on: https://uxdesign.cc/how-to-trap-focus-inside-modal-to-make-it-ada-compliant-6a50f9a70700
=> Add delete modal for my connections

composer.lock, config/packages/security.yaml, src/OpenConext/AttributeAggregationApiClientBundle/DependencyInjection/Configuration.php, src/OpenConext/EngineBlockApiClientBundle/DependencyInjection/Configuration.php, src/OpenConext/ProfileBundle/DependencyInjection/Configuration.php, src/OpenConext/ProfileBundle/Resources/config/routing.yml, src/OpenConext/ProfileBundle/Resources/views/MySurfConext/data-download.html.twig, src/OpenConext/ProfileBundle/Security/Firewall/SamlListener.php, src/OpenConext/ProfileBundle/Twig/LocaleExtension.php, src/OpenConext/UserLifecycleApiClientBundle/DependencyInjection/Configuration.php
Remove as many deprecation warnings as humanly possible. A large amount of warnings are left in place as they are generated by the Stepup-bundle
=> Deprecation resolutions

assets/css/pages/myServices/loginDetails.scss, templates/base.html.twig
Prior to this change, there was a regression in the styling of login-details.  The label received too little space, meaning it was split over two rows.
This change ensures the label is fully on one row again.
=> Ensure login details is on one row

src/OpenConext/ProfileBundle/Resources/views/helpers/modal.html.twig
Prior to this change, the element triggering a modal did not have the correct role.  This lead to a somewhat weird announcement in a screenreader.
This change ensures the right role is added.
=> Apply correct role to modal triggering button

cypress/plugins/index.js, cypress/support/index.js, package-lock.json, package.json, src/OpenConext/ProfileBundle/Controller/MyServicesController.php, src/OpenConext/ProfileBundle/Resources/config/services.yml, src/OpenConext/ProfileBundle/Twig/LocaleExtension.php, templates/base.html.twig
Prior to this change there wasn't much logging when cypress ran in headless mode.  We also had some rules in html-validate which threw incorrect errors.  As a result those were configured to only throw warnings. Thankfully, those errors were solved by the project maintainer of html-validate.
This change:
- adds a plugin to increase logging in headless mode.
- upgrades html-validate en cypress-html-validate to the new & improved version.
- ensures the warnings are errors again and adds a specific rule for heading level.
- fixes an error found when testing for the above fix: it turns out there was no document language set on the html tag.  Now there is.
=> Improve cypress tests

assets/css/pages/myServices/serviceList.scss
Prior to this change, the icons showed up black in firefox.
This change ensures they are blue in firefox as well.
Ticket on pivotal: https://www.pivotaltracker.com/story/show/180095726
=> Ensure support icons have the right color

assets/js/tooltip.js, src/OpenConext/ProfileBundle/Resources/views/MyServices/AttributeList/idp.html.twig, src/OpenConext/ProfileBundle/Resources/views/MyServices/ConsentList/consent-list.html.twig
Prior to this change, the id for the input element toggling the tooltip was generated incorrectly.  This made all labels of different organisations toggle the same disclosure modal.
This change uses the organizationId as an id for the input.  Thus ensuring that the modal is toggled correctly.
Pivotal ticket: https://www.pivotaltracker.com/story/show/180095824
=> Ensure the something incorrect disclosure is shown

src/OpenConext/ProfileBundle/Controller/IntroductionController.php, src/OpenConext/ProfileBundle/Controller/LocaleController.php, src/OpenConext/ProfileBundle/Controller/MyConnectionsController.php, src/OpenConext/ProfileBundle/Controller/MyProfileController.php, src/OpenConext/ProfileBundle/Controller/MyServicesController.php, src/OpenConext/ProfileBundle/Controller/MySurfConextController.php, src/OpenConext/ProfileBundle/Controller/SamlController.php, src/OpenConext/ProfileBundle/Security/Firewall/SamlListener.php
These are the kinds of situations that are just run of the mill (show a specific
page, mostly) and do not need to be logged above the passthrough level. In the
development environment one can override the passthrouh level to show these
if necessary.
=> Downgrade 'normal operation' log messages to info

src/OpenConext/ProfileBundle/Resources/views/MyServices/AttributeList/idp.html.twig
hasLogo() does not exist so is always false, hasUrl() does exist.
=> Fix IdP logo display in My Services overview

.github/workflows/tag-release.yml, README.md, bin/makeRelease.sh, docker-compose-tag-release.yml
In this workflow an incoming tag is triggering the makeRelease script. The output of this script (the artifacts) are used to create a new release page on the projects GitHub releases page. The artifacts are then uploaded to that new release.
The one thing remaining is to add the release notes to the release. This is now set with a small placeholder message
=> Create release artifacts when project is tagged

config/legacy/parameters.yaml.dist, config/packages/framework.yaml, config/services.yaml
When sticky sessions are not an option it might be usefull to store sessions in the database. This adds a configuration parameter to do so.
The default is still file based session storage
=> Add the option to store sessions in the database

src/OpenConext/ProfileBundle/Security/Firewall/SamlListener.php
Previously we've reduced the loglevel of a number of events to info level,
but an actual login action deserves to stand out at notice level. We
add the username of the authenticated user so that if anything goes wrong
or is reported, we can find out who it was.
Before:
```
Mar  1 12:07:20 t06.ams.surfconext.nl openconext-profile[26631]: app.INFO: Authentication succeeded, redirecting to original location [] []
```
After:
```
Mar  1 12:28:15 t06.ams.surfconext.nl openconext-profile[30817]: app.NOTICE: Authentication succeeded, redirecting to original location {"user":"urn:collab:person:surfnet.nl:kinkhorst"} []
```
=> Log which user authenticated to the application.

assets/css/pages/myServices/serviceList.scss, assets/css/shared/shared.scss, assets/css/shared/svg.scss, config/packages/dev/nelmio_security.yaml, src/OpenConext/ProfileBundle/Resources/views/svgs/email-action-unread.svg, src/OpenConext/ProfileBundle/Resources/views/svgs/network-information.svg
SVG images that are included on the page would trigger CSP usafe inline errors. Loosening the CSP would open us to a host of other vulnerabilities. So fixing the SVG's was the way to go.
Having the inline styles in a dedicated stylesheet proved to be the most pragmatic solution. Thanks @Badlapje for thinking out of the box with me on this one! 
Bugreport: https://www.pivotaltracker.com/story/show/180407180
=> Prevent unsafe-inline CSP errors on SVG images

composer.json, composer.lock, src/OpenConext/EngineBlockApiClientBundle/HealthCheck/ApiHealthCheck.php
By upgrading the Monitor Bundle to version 3.1.0. The internal/info and internal/health routes have become available.
https://github.com/OpenConext/Monitor-bundle/pull/8/
https://www.pivotaltracker.com/story/show/181884474
=> Expose `info` and `health` on `/internal` by updating the Monitor bundle

assets/css/components/list.scss, src/OpenConext/EngineBlockApiClientBundle/Value/ConsentListFactory.php, src/OpenConext/Profile/Value/Consent/ServiceProvider.php, src/OpenConext/ProfileBundle/Resources/views/MyServices/ConsentList/consent-list.html.twig, src/OpenConext/ProfileBundle/Resources/views/MyServices/ConsentList/login-details.html.twig, translations/messages.en.php, translations/messages.nl.php, translations/messages.pt.php
1. It is shown on the accordeon that also displays the SP display name
2. It is listed in the Login details section
Translations where added for the 'offered by label'
Styling was changed. The blue title has been blackened
See: https://www.pivotaltracker.com/story/show/176872837
Requires: https://github.com/OpenConext/OpenConext-engineblock/pull/1186
=> Show the organization name on the my-services page

.github/workflows/cleanup.yml, .github/workflows/main.yml, .github/workflows/test-integration.yml, src/OpenConext/EngineBlockApiClientBundle/Tests/Value/ConsentListFactoryTest.php, src/OpenConext/Profile/Tests/Value/SpecifiedConsentListTest.php, src/OpenConext/Profile/Tests/Value/SpecifiedConsentTest.php, src/OpenConext/Profile/Value/DisplayName.php, src/OpenConext/ProfileBundle/Security/Firewall/SamlListener.php, src/OpenConext/ProfileBundle/Tests/Service/AttributeReleasePolicyServiceTest.php
Turns out, test-integration GH Actions where not triggered on PR's aimed at develop :blush: 
This PR addresses that issue, and fixes the QA issues raised by not running the test-integration on the last couple of PR's that have been merged.
Thanks @VadimSchmitz for noting this issue!
=> Enable test-integration runs on develop

.env.dist, .github/workflows/test-integration.yml, composer.json, composer.lock, config/bundles.php, config/packages/dev/swiftmailer.yaml, config/packages/mailer.yaml, config/packages/swiftmailer.yaml, config/packages/test/swiftmailer.yaml, src/OpenConext/ProfileBundle/Service/AttributeSupportMailService.php, src/OpenConext/ProfileBundle/Service/InformationRequestMailService.php, symfony.lock
The work done in this Pull request are:
- Remove Swiftmailer
- Configure Symony mailer
- Replace Swiftmailer with Symfony mailer
- Update lock files
=> Replace deprecated Swiftmailer with Symfony mailer

assets/css/components/modal-window.scss, src/OpenConext/EngineBlockApiClientBundle/Http/JsonApiClient.php, src/OpenConext/ProfileBundle/Resources/views/MyServices/ConsentList/delete-button-and-modal.html.twig, src/OpenConext/ProfileBundle/Resources/views/MyServices/ConsentList/login-details.html.twig, translations/messages.en.php, translations/messages.nl.php, translations/messages.pt.php
Most of the heavy lifting of this feature was already implemented by @Badlapje. The final integration needed some minor tweaking to get it all to work.
Reminder: use the `remove_consent_enabled` feature flag in config/legacy/parameters.yml to toggle the remove feature.
See: #185 
See: https://www.pivotaltracker.com/story/show/179490276
Requires: https://github.com/OpenConext/OpenConext-engineblock/pull/1160
=> Support consent removal in Profile

src/Kernel.php
The swithed order was introduced in 3.0 but for no apparent reason, since var/cache/<env> is still the default used everywhere, this was likely by mistake (maybe from copying [this example](https://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-cache-directory)?) so change it back so it matches what is customary.
=> Make the cache path `var/cache/prod` again instead of `var/prod/cache`.

.github/workflows/main.yml
This adds packages:write permissions to the workflow that builds and publishes the docker image.
=> GHA: Add package write permissions to the docker build workflow

config/packages/monolog.yaml, src/OpenConext/Infrastructure/Monolog/Formatter/JsonFormatter.php
Add a JsonFormatter to the project and use it in monolog
=> Add JsonFormatter

ci/qa/phpstan-baseline.neon, src/OpenConext/Kernel.php, src/OpenConext/Profile/Tests/Value/SpecifiedConsentListTest.php, src/OpenConext/Profile/Value/SpecifiedConsentList.php
So you can find the service "iotroam" near "Internal Gitlab" and not after the "Z".
=> When sorting SPs by name, do so case insentively

src/OpenConext/Profile/Tests/Value/ArpTest.php, src/OpenConext/Profile/Tests/fixture/arp-response.json, src/OpenConext/Profile/Value/Arp.php
Added a local function to remove al irrelevant attributes from the ARP returned from the API calls. This way, the API can "grow" without erroring the Arp class
=> Add ARP santizer

config/packages/surfnet_saml.yaml
This value has to be set, otherwise the service is initiated with NULL (which fails typing)
Other possible improvements:
- Config the service with false in the `src/Resources/config/services.yaml` 
- Type the `$ignoreUnkonwnAttributes` variable as bool in the constructor of AttributeDictionary
=> Set ignore_unknown_attributes to true
